### ISSUE TITLE
Silent Mode

### ISSUE THREAD

**Issue by steve-goley** [JustasB/linetimer#1]
It'd be great to have a silent mode option so that you could turn off the timing with a variable. Something like this
`CodeTimer('test', silent=False):`
or 
`CodeTimer('test', silent=True):`

**Comment by JustasB** [comment]
That's a great idea @steve-goley. 

Would you mind checking in a quick PR?

**Comment by JustasB** [comment]
@steve-goley I made the change. You can get it with the latest version: `pip install linetimer==0.1.1`

**Comment by yashkant** [comment]
How about a global level silent mode too?

**Comment by yashkant** [comment]
Thanks for the great repo btw!
