### ISSUE TITLE
Log each line

### ISSUE THREAD

**Issue by frankiedrake** [JustasB/linetimer#10]
I came here from googling, I'm searching for a solution that lets to log timings after each line of a function execution, e.g. if there's 5 lines of code in a function, than there will be 5 print (log) statements displayed

**Comment by chitralverma** [comment]
There are 2 simple ways to do this,

`from linetimer import CodeTimer`

**Option 1**

```
for i in range(10):
    with CodeTimer('line iter {}'.format(i)):
        print(i)  # line/ block to test for
```

**Option 2**

```
def time_this(line_of_code):
    with CodeTimer('line_of_code'):
        line_of_code  # line/ block to test for
```
and use it like,

`time_this(print("a"))`

Hope this helps.

**Comment by frankiedrake** [comment]
Thanks, but I guess you didn't get my idea, I want it to be done automatically. For example having a function `foo`:
```
def foo():
    some_slow_calculation(...)
    open('or_opening_a_file')
    requests.post('or doing some post request')

def time_this(line_of_code):
    with CodeTimer('foo'):
        foo()  # there will be 3 lines of output (for each line in foo)
```

**Comment by JustasB** [comment]
Hi @frankiedrake,

The use case you're describing is outside the scope of this package. To get line-by-line timings, I suggest you try the `line_profiler` package. There are some examples here: https://stackoverflow.com/a/43376466/407108

I hope that helps,

Justas
