### ISSUE TITLE
Allow time unit specification

### ISSUE THREAD

**Issue by chitralverma** [JustasB/linetimer#2]
I believe this utility can be of great use in a lot of places, specially when the 'slow_function()' is really slow, as in hours. Currently, for such cases the result is always in milliseconds, which then has to be manually converted back to the appropriate time unit.

It'd be great to have a time unit specification so that the manual conversion step is skipped. Will look like this in print,

```
with CodeTimer('Block', unit='h'):
   slow_function()
```
 
Corresponding to this, the output string has to be changed, for example,

> Code block 'Block' took: 2.382 h

I've made the necessary changes and added some tests, will raise a PR shortly.
Let me know your thoughts on this, thanks.

**Comment by chitralverma** [comment]
@JustasB raised PR #3 for this issue.

**Comment by JustasB** [comment]
This is a great idea @chitralverma. Thank you for the PR. I will merge it.

**Comment by JustasB** [comment]
The new version is available on pip
