### ISSUE TITLE
Support as function wrapper?

### ISSUE THREAD

**Issue by devanl** [JustasB/linetimer#6]
Can we add support for this to be used directly as a function wrapper?

**Comment by JustasB** [comment]
Hi @devanl, Can you provide a code sample of how you would want to use it?

**Comment by devanl** [comment]
Certainly, thanks for asking!

``` Python
@linetimer()
def foo(i, j=0):
  pass

foo(5, j=3)
```

> Code block 'foo(5, j=3)' took: 0.73970 ms

**Comment by JustasB** [comment]
Would you be ok with output that does not reprint the function arguments? 

I'm concerned that the printed line would be too long if the arguments are long/complex (e.g. dicts or lists). The output would look like this:

> Code block 'foo' took: 0.73970 ms

**Comment by devanl** [comment]
I'll take what I can get ;)
I was merely thinking if the args are shown then multiple calls can be differentiated.  Perhaps an argument to the decorator to show args?

``` Python
@linetimer(show_ags=False)
def foo(i, j=0):
  pass

foo(5, j=3)
```
>Code block 'foo()' took: 0.73970 ms


``` Python
@linetimer(show_ags=True)
def foo(i, j=0):
  pass

foo(5, j=3)
```
>Code block 'foo(5, j=3)' took: 0.73970 ms

**Comment by JustasB** [comment]
Give it a try with the new version:

```
pip uninstall linetimer
pip install linetimer
```

Then take a look at examples in the bottom of the repo home page: https://github.com/JustasB/linetimer

and also in the unit tests: https://github.com/JustasB/linetimer/blob/master/tests/test_CodeTimer.py#L142

**Comment by devanl** [comment]
This is perfect, thanks!
